### ISSUE TITLE
Animated Example

### ISSUE THREAD

**Issue by colinramsay** [brentvatne/react-native-overlay#8]
I found a Stack Overflow question which is trying to make a dropdown menu overlay:

![http://i.stack.imgur.com/lJdpZ.gif](http://i.stack.imgur.com/lJdpZ.gif)

http://stackoverflow.com/questions/30638739/transparent-overlay-in-react-native

Looks like this would be a good application for react-native-overlay?

**Comment by brentvatne** [comment]
@colinramsay - you could definitely use it here, although I'm not sure it's totally necessary because you could just position a view with absolute positioning as the last component in the app [like how the WarningBox is implemented](https://github.com/facebook/react-native/blob/1120769f1ba1319db2a2d739f9f3eaed835072d1/Libraries/ReactIOS/renderApplication.ios.js#L48-L61)
